#!/usr/bin/env node
// Download product photos listed in tools/photo-urls.txt into assets/products/ and register them in js/data/photos.js.
//
//   node tools/fetch-photos.mjs            # download everything listed
//   node tools/fetch-photos.mjs --force    # re-download files that already exist
//   node tools/fetch-photos.mjs --dry      # only show what would happen
//
// photo-urls.txt format, one product per line (blank lines and # comments are ignored):
//   <product-id> <image-url> [source / credit text]
// Requires Node 18+. No dependencies. Run it on a machine with normal internet access.
import { readFile, writeFile, mkdir, access, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LIST = path.join(root, 'tools/photo-urls.txt');
const OUT = path.join(root, 'assets/products');
const REGISTRY = path.join(root, 'js/data/photos.js');
const CREDITS = path.join(root, 'CREDITS.md');
const args = new Set(process.argv.slice(2));
const FORCE = args.has('--force'), DRY = args.has('--dry');
const EXT = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp', 'image/avif': 'avif', 'image/gif': 'gif' };
const exists = (p) => access(p).then(() => true, () => false);

// Known product ids come from the catalogue, so typos are caught early.
const { PRODUCTS } = await import(path.join(root, 'js/data/products.js'));
const ids = new Set(PRODUCTS.map((p) => p.id));

const lines = (await readFile(LIST, 'utf8')).split(/\r?\n/);
const jobs = [];
lines.forEach((raw, i) => {
  const line = raw.trim();
  if (!line || line.startsWith('#')) return;
  const m = line.match(/^(\S+)\s+(https?:\/\/\S+)(?:\s+(.*))?$/);
  if (!m) return console.warn(`line ${i + 1}: expected "<id> <url> [credit]", skipped`);
  const [, id, url, credit = ''] = m;
  if (!ids.has(id)) return console.warn(`line ${i + 1}: unknown product id "${id}", skipped`);
  jobs.push({ id, url, credit });
});
if (!jobs.length) { console.log('No URLs found in tools/photo-urls.txt. Add lines like:\n  keychron-q1-pro https://example.com/q1.jpg Photo by Someone, CC BY 4.0'); process.exit(0); }

await mkdir(OUT, { recursive: true });
const existing = await readdir(OUT);
const have = (id) => existing.find((f) => f.replace(/\.[a-z0-9]+$/i, '') === id && !f.endsWith('.md'));
const done = {};   // id -> filename
const credits = {}; // id -> text
let ok = 0, failed = 0;

for (const { id, url, credit } of jobs) {
  const prior = have(id);
  if (prior && !FORCE) { done[id] = prior; credits[id] = credit; console.log(`skip   ${id} (already ${prior}; use --force to replace)`); continue; }
  if (DRY) { console.log(`would  ${id} <- ${url}`); continue; }
  try {
    const res = await fetch(url, { redirect: 'follow', headers: { 'user-agent': 'Mozilla/5.0 (keyforge photo fetcher)', accept: 'image/*' } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const type = (res.headers.get('content-type') || '').split(';')[0].trim().toLowerCase();
    const ext = EXT[type] || path.extname(new URL(url).pathname).slice(1).toLowerCase().replace('jpeg', 'jpg');
    if (!EXT[type] && !['jpg', 'png', 'webp', 'avif', 'gif'].includes(ext)) throw new Error(`not an image (${type || 'unknown type'})`);
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length < 2000) throw new Error('file is suspiciously small');
    const file = `${id}.${EXT[type] || ext}`;
    await writeFile(path.join(OUT, file), buf);
    done[id] = file; credits[id] = credit; ok++;
    console.log(`ok     ${id} -> ${file} (${(buf.length / 1024).toFixed(0)} KB)`);
  } catch (e) {
    failed++;
    console.warn(`FAILED ${id}: ${e.message}  (${url})`);
  }
}
if (DRY) process.exit(0);

// Merge with photos already registered in assets/products so nothing is lost.
for (const f of await readdir(OUT)) {
  const m = f.match(/^([a-z0-9-]+)\.(jpg|png|webp|avif|gif)$/i);
  if (m && ids.has(m[1])) done[m[1]] ||= f;
}
const body = Object.keys(done).sort().map((id) => `  '${id}': '${done[id]}',`).join('\n');
await writeFile(REGISTRY, `// Registry of real product photos that exist in assets/products/. Map product id -> filename.
// Products without an entry use generated SVG art (no failed network requests).
// Generated by tools/fetch-photos.mjs; you can also edit it by hand.
export const PHOTOS = {
${body}${body ? '\n' : ''}};
`);

const credited = Object.entries(credits).filter(([, c]) => c);
if (credited.length) {
  const name = (id) => PRODUCTS.find((p) => p.id === id)?.name || id;
  await writeFile(CREDITS, `# Photo credits\n\nProduct photos used for testing. Check each source's licence before any public or commercial use.\n\n${credited.map(([id, c]) => `- **${name(id)}**: ${c}`).join('\n')}\n`);
}
console.log(`\nDone: ${ok} downloaded, ${failed} failed, ${Object.keys(done).length} registered in js/data/photos.js.`);
if (failed) process.exitCode = 1;
